version: '3.4'

services:
  test_db:
    image: mariadb
    container_name: test_db
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: test_laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - testDataDB:/var/lib/mysql
    ports:
      - 3306:3306
  test_php:
    image: php:8.2-fpm-to-laravel
    container_name: test_php
    volumes:
      - ./laravel-json-api/:/app
    depends_on:
      - test_db

  test_nginx:
    image: nginx:latest
    container_name: test_nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel-json-api/public/:/app/public
      - ./laravel-json-api/storage/:/app/storage/
      - ./react-material-laravel-app/build/:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - test_php
    links:
      - test_php
volumes:
  testDataDB:
    driver: local

